version: '3.8'
services:
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass local-redis-auth
    volumes: 
      - cache:/data
volumes:
  redis:
    driver: local