version: "3"

services:
  seq:
    image: datalust/seq:latest
    deploy:
      resources:
        limits:
          memory: 14G
        reservations:
          memory: 14G
    volumes:
      - seqlog:/data
    environment:
      - ACCEPT_EULA=Y
    ports:
      - '5341:80'
volumes:
  seqlog:
    driver: local